// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(grunt) {
    grunt.loadNpmTasks("grunt-bower-task");
    grunt.initConfig({
      pkg: grunt.file.readJSON("package.json"),
      bower: {
        install: {
          options: {
            targetDir: './public/',
            layout: 'byType',
            install: true,
            verbose: false,
            cleanTargetDir: false,
            cleanBowerDir: false
          }
        }
      }
    });
    return grunt.registerTask("default", ["bower:install"]);
  };

}).call(this);
