// Generated by CoffeeScript 1.6.3
(function() {
  var ldap, password, username;

  username = "uid=admin,ou=system";

  password = "secret";

  ldap = new (require("LDAP"))({
    uri: "ldap://localhost:10389",
    version: 3,
    binddn: username,
    password: password
  });

  ldap.open(function(err) {
    if (err) {
      console.error(err);
      return;
    }
    return ldap.search({
      base: username,
      scope: 2
    }, function(err, data) {
      if (err) {
        console.error(err);
        return;
      }
      return console.log(data);
    });
  });

}).call(this);
